#include "cpu.h"

void CPU::cbopcode00() {}
void CPU::cbopcode01() {}
void CPU::cbopcode02() {}
void CPU::cbopcode03() {}
void CPU::cbopcode04() {}
void CPU::cbopcode05() {}
void CPU::cbopcode06() {}
void CPU::cbopcode07() {}
void CPU::cbopcode08() {}
void CPU::cbopcode09() {}
void CPU::cbopcode0A() {}
void CPU::cbopcode0B() {}
void CPU::cbopcode0C() {}
void CPU::cbopcode0D() {}
void CPU::cbopcode0E() {}
void CPU::cbopcode0F() {}

void CPU::cbopcode10() {}
void CPU::cbopcode11() {}
void CPU::cbopcode12() {}
void CPU::cbopcode13() {}
void CPU::cbopcode14() {}
void CPU::cbopcode15() {}
void CPU::cbopcode16() {}
void CPU::cbopcode17() {}
void CPU::cbopcode18() {}
void CPU::cbopcode19() {}
void CPU::cbopcode1A() {}
void CPU::cbopcode1B() {}
void CPU::cbopcode1C() {}
void CPU::cbopcode1D() {}
void CPU::cbopcode1E() {}
void CPU::cbopcode1F() {}

void CPU::cbopcode20() {}
void CPU::cbopcode21() {}
void CPU::cbopcode22() {}
void CPU::cbopcode23() {}
void CPU::cbopcode24() {}
void CPU::cbopcode25() {}
void CPU::cbopcode26() {}
void CPU::cbopcode27() {}
void CPU::cbopcode28() {}
void CPU::cbopcode29() {}
void CPU::cbopcode2A() {}
void CPU::cbopcode2B() {}
void CPU::cbopcode2C() {}
void CPU::cbopcode2D() {}
void CPU::cbopcode2E() {}
void CPU::cbopcode2F() {}

void CPU::cbopcode30() {}
void CPU::cbopcode31() {}
void CPU::cbopcode32() {}
void CPU::cbopcode33() {}
void CPU::cbopcode34() {}
void CPU::cbopcode35() {}
void CPU::cbopcode36() {}
void CPU::cbopcode37() {}
void CPU::cbopcode38() {}
void CPU::cbopcode39() {}
void CPU::cbopcode3A() {}
void CPU::cbopcode3B() {}
void CPU::cbopcode3C() {}
void CPU::cbopcode3D() {}
void CPU::cbopcode3E() {}
void CPU::cbopcode3F() {}

void CPU::cbopcode40() {}
void CPU::cbopcode41() {}
void CPU::cbopcode42() {}
void CPU::cbopcode43() {}
void CPU::cbopcode44() {}
void CPU::cbopcode45() {}
void CPU::cbopcode46() {}
void CPU::cbopcode47() {}
void CPU::cbopcode48() {}
void CPU::cbopcode49() {}
void CPU::cbopcode4A() {}
void CPU::cbopcode4B() {}
void CPU::cbopcode4C() {}
void CPU::cbopcode4D() {}
void CPU::cbopcode4E() {}
void CPU::cbopcode4F() {}

void CPU::cbopcode50() {}
void CPU::cbopcode51() {}
void CPU::cbopcode52() {}
void CPU::cbopcode53() {}
void CPU::cbopcode54() {}
void CPU::cbopcode55() {}
void CPU::cbopcode56() {}
void CPU::cbopcode57() {}
void CPU::cbopcode58() {}
void CPU::cbopcode59() {}
void CPU::cbopcode5A() {}
void CPU::cbopcode5B() {}
void CPU::cbopcode5C() {}
void CPU::cbopcode5D() {}
void CPU::cbopcode5E() {}
void CPU::cbopcode5F() {}

void CPU::cbopcode60() {}
void CPU::cbopcode61() {}
void CPU::cbopcode62() {}
void CPU::cbopcode63() {}
void CPU::cbopcode64() {}
void CPU::cbopcode65() {}
void CPU::cbopcode66() {}
void CPU::cbopcode67() {}
void CPU::cbopcode68() {}
void CPU::cbopcode69() {}
void CPU::cbopcode6A() {}
void CPU::cbopcode6B() {}
void CPU::cbopcode6C() {}
void CPU::cbopcode6D() {}
void CPU::cbopcode6E() {}
void CPU::cbopcode6F() {}

void CPU::cbopcode70() {}
void CPU::cbopcode71() {}
void CPU::cbopcode72() {}
void CPU::cbopcode73() {}
void CPU::cbopcode74() {}
void CPU::cbopcode75() {}
void CPU::cbopcode76() {}
void CPU::cbopcode77() {}
void CPU::cbopcode78() {}
void CPU::cbopcode79() {}
void CPU::cbopcode7A() {}
void CPU::cbopcode7B() {}
void CPU::cbopcode7C() {}
void CPU::cbopcode7D() {}
void CPU::cbopcode7E() {}
void CPU::cbopcode7F() {}

void CPU::cbopcode80() {}
void CPU::cbopcode81() {}
void CPU::cbopcode82() {}
void CPU::cbopcode83() {}
void CPU::cbopcode84() {}
void CPU::cbopcode85() {}
void CPU::cbopcode86() {}
void CPU::cbopcode87() {}
void CPU::cbopcode88() {}
void CPU::cbopcode89() {}
void CPU::cbopcode8A() {}
void CPU::cbopcode8B() {}
void CPU::cbopcode8C() {}
void CPU::cbopcode8D() {}
void CPU::cbopcode8E() {}
void CPU::cbopcode8F() {}

void CPU::cbopcode90() {}
void CPU::cbopcode91() {}
void CPU::cbopcode92() {}
void CPU::cbopcode93() {}
void CPU::cbopcode94() {}
void CPU::cbopcode95() {}
void CPU::cbopcode96() {}
void CPU::cbopcode97() {}
void CPU::cbopcode98() {}
void CPU::cbopcode99() {}
void CPU::cbopcode9A() {}
void CPU::cbopcode9B() {}
void CPU::cbopcode9C() {}
void CPU::cbopcode9D() {}
void CPU::cbopcode9E() {}
void CPU::cbopcode9F() {}

void CPU::cbopcodeA0() {}
void CPU::cbopcodeA1() {}
void CPU::cbopcodeA2() {}
void CPU::cbopcodeA3() {}
void CPU::cbopcodeA4() {}
void CPU::cbopcodeA5() {}
void CPU::cbopcodeA6() {}
void CPU::cbopcodeA7() {}
void CPU::cbopcodeA8() {}
void CPU::cbopcodeA9() {}
void CPU::cbopcodeAA() {}
void CPU::cbopcodeAB() {}
void CPU::cbopcodeAC() {}
void CPU::cbopcodeAD() {}
void CPU::cbopcodeAE() {}
void CPU::cbopcodeAF() {}

void CPU::cbopcodeB0() {}
void CPU::cbopcodeB1() {}
void CPU::cbopcodeB2() {}
void CPU::cbopcodeB3() {}
void CPU::cbopcodeB4() {}
void CPU::cbopcodeB5() {}
void CPU::cbopcodeB6() {}
void CPU::cbopcodeB7() {}
void CPU::cbopcodeB8() {}
void CPU::cbopcodeB9() {}
void CPU::cbopcodeBA() {}
void CPU::cbopcodeBB() {}
void CPU::cbopcodeBC() {}
void CPU::cbopcodeBD() {}
void CPU::cbopcodeBE() {}
void CPU::cbopcodeBF() {}

void CPU::cbopcodeC0() {}
void CPU::cbopcodeC1() {}
void CPU::cbopcodeC2() {}
void CPU::cbopcodeC3() {}
void CPU::cbopcodeC4() {}
void CPU::cbopcodeC5() {}
void CPU::cbopcodeC6() {}
void CPU::cbopcodeC7() {}
void CPU::cbopcodeC8() {}
void CPU::cbopcodeC9() {}
void CPU::cbopcodeCA() {}
void CPU::cbopcodeCB() {}
void CPU::cbopcodeCC() {}
void CPU::cbopcodeCD() {}
void CPU::cbopcodeCE() {}
void CPU::cbopcodeCF() {}

void CPU::cbopcodeD0() {}
void CPU::cbopcodeD1() {}
void CPU::cbopcodeD2() {}
void CPU::cbopcodeD3() {}
void CPU::cbopcodeD4() {}
void CPU::cbopcodeD5() {}
void CPU::cbopcodeD6() {}
void CPU::cbopcodeD7() {}
void CPU::cbopcodeD8() {}
void CPU::cbopcodeD9() {}
void CPU::cbopcodeDA() {}
void CPU::cbopcodeDB() {}
void CPU::cbopcodeDC() {}
void CPU::cbopcodeDD() {}
void CPU::cbopcodeDE() {}
void CPU::cbopcodeDF() {}

void CPU::cbopcodeE0() {}
void CPU::cbopcodeE1() {}
void CPU::cbopcodeE2() {}
void CPU::cbopcodeE3() {}
void CPU::cbopcodeE4() {}
void CPU::cbopcodeE5() {}
void CPU::cbopcodeE6() {}
void CPU::cbopcodeE7() {}
void CPU::cbopcodeE8() {}
void CPU::cbopcodeE9() {}
void CPU::cbopcodeEA() {}
void CPU::cbopcodeEB() {}
void CPU::cbopcodeEC() {}
void CPU::cbopcodeED() {}
void CPU::cbopcodeEE() {}
void CPU::cbopcodeEF() {}

void CPU::cbopcodeF0() {}
void CPU::cbopcodeF1() {}
void CPU::cbopcodeF2() {}
void CPU::cbopcodeF3() {}
void CPU::cbopcodeF4() {}
void CPU::cbopcodeF5() {}
void CPU::cbopcodeF6() {}
void CPU::cbopcodeF7() {}
void CPU::cbopcodeF8() {}
void CPU::cbopcodeF9() {}
void CPU::cbopcodeFA() {}
void CPU::cbopcodeFB() {}
void CPU::cbopcodeFC() {}
void CPU::cbopcodeFD() {}
void CPU::cbopcodeFE() {}
void CPU::cbopcodeFF() {}