#include "cpu.h"

void CPU::CbOpcode00() {}
void CPU::CbOpcode01() {}
void CPU::CbOpcode02() {}
void CPU::CbOpcode03() {}
void CPU::CbOpcode04() {}
void CPU::CbOpcode05() {}
void CPU::CbOpcode06() {}
void CPU::CbOpcode07() {}
void CPU::CbOpcode08() {}
void CPU::CbOpcode09() {}
void CPU::CbOpcode0A() {}
void CPU::CbOpcode0B() {}
void CPU::CbOpcode0C() {}
void CPU::CbOpcode0D() {}
void CPU::CbOpcode0E() {}
void CPU::CbOpcode0F() {}

void CPU::CbOpcode10() {}
void CPU::CbOpcode11() {}
void CPU::CbOpcode12() {}
void CPU::CbOpcode13() {}
void CPU::CbOpcode14() {}
void CPU::CbOpcode15() {}
void CPU::CbOpcode16() {}
void CPU::CbOpcode17() {}
void CPU::CbOpcode18() {}
void CPU::CbOpcode19() {}
void CPU::CbOpcode1A() {}
void CPU::CbOpcode1B() {}
void CPU::CbOpcode1C() {}
void CPU::CbOpcode1D() {}
void CPU::CbOpcode1E() {}
void CPU::CbOpcode1F() {}

void CPU::CbOpcode20() {}
void CPU::CbOpcode21() {}
void CPU::CbOpcode22() {}
void CPU::CbOpcode23() {}
void CPU::CbOpcode24() {}
void CPU::CbOpcode25() {}
void CPU::CbOpcode26() {}
void CPU::CbOpcode27() {}
void CPU::CbOpcode28() {}
void CPU::CbOpcode29() {}
void CPU::CbOpcode2A() {}
void CPU::CbOpcode2B() {}
void CPU::CbOpcode2C() {}
void CPU::CbOpcode2D() {}
void CPU::CbOpcode2E() {}
void CPU::CbOpcode2F() {}

void CPU::CbOpcode30() {}
void CPU::CbOpcode31() {}
void CPU::CbOpcode32() {}
void CPU::CbOpcode33() {}
void CPU::CbOpcode34() {}
void CPU::CbOpcode35() {}
void CPU::CbOpcode36() {}
void CPU::CbOpcode37() {}
void CPU::CbOpcode38() {}
void CPU::CbOpcode39() {}
void CPU::CbOpcode3A() {}
void CPU::CbOpcode3B() {}
void CPU::CbOpcode3C() {}
void CPU::CbOpcode3D() {}
void CPU::CbOpcode3E() {}
void CPU::CbOpcode3F() {}

void CPU::CbOpcode40() {}
void CPU::CbOpcode41() {}
void CPU::CbOpcode42() {}
void CPU::CbOpcode43() {}
void CPU::CbOpcode44() {}
void CPU::CbOpcode45() {}
void CPU::CbOpcode46() {}
void CPU::CbOpcode47() {}
void CPU::CbOpcode48() {}
void CPU::CbOpcode49() {}
void CPU::CbOpcode4A() {}
void CPU::CbOpcode4B() {}
void CPU::CbOpcode4C() {}
void CPU::CbOpcode4D() {}
void CPU::CbOpcode4E() {}
void CPU::CbOpcode4F() {}

void CPU::CbOpcode50() {}
void CPU::CbOpcode51() {}
void CPU::CbOpcode52() {}
void CPU::CbOpcode53() {}
void CPU::CbOpcode54() {}
void CPU::CbOpcode55() {}
void CPU::CbOpcode56() {}
void CPU::CbOpcode57() {}
void CPU::CbOpcode58() {}
void CPU::CbOpcode59() {}
void CPU::CbOpcode5A() {}
void CPU::CbOpcode5B() {}
void CPU::CbOpcode5C() {}
void CPU::CbOpcode5D() {}
void CPU::CbOpcode5E() {}
void CPU::CbOpcode5F() {}

void CPU::CbOpcode60() {}
void CPU::CbOpcode61() {}
void CPU::CbOpcode62() {}
void CPU::CbOpcode63() {}
void CPU::CbOpcode64() {}
void CPU::CbOpcode65() {}
void CPU::CbOpcode66() {}
void CPU::CbOpcode67() {}
void CPU::CbOpcode68() {}
void CPU::CbOpcode69() {}
void CPU::CbOpcode6A() {}
void CPU::CbOpcode6B() {}
void CPU::CbOpcode6C() {}
void CPU::CbOpcode6D() {}
void CPU::CbOpcode6E() {}
void CPU::CbOpcode6F() {}

void CPU::CbOpcode70() {}
void CPU::CbOpcode71() {}
void CPU::CbOpcode72() {}
void CPU::CbOpcode73() {}
void CPU::CbOpcode74() {}
void CPU::CbOpcode75() {}
void CPU::CbOpcode76() {}
void CPU::CbOpcode77() {}
void CPU::CbOpcode78() {}
void CPU::CbOpcode79() {}
void CPU::CbOpcode7A() {}
void CPU::CbOpcode7B() {}
void CPU::CbOpcode7C() {}
void CPU::CbOpcode7D() {}
void CPU::CbOpcode7E() {}
void CPU::CbOpcode7F() {}

void CPU::CbOpcode80() {}
void CPU::CbOpcode81() {}
void CPU::CbOpcode82() {}
void CPU::CbOpcode83() {}
void CPU::CbOpcode84() {}
void CPU::CbOpcode85() {}
void CPU::CbOpcode86() {}
void CPU::CbOpcode87() {}
void CPU::CbOpcode88() {}
void CPU::CbOpcode89() {}
void CPU::CbOpcode8A() {}
void CPU::CbOpcode8B() {}
void CPU::CbOpcode8C() {}
void CPU::CbOpcode8D() {}
void CPU::CbOpcode8E() {}
void CPU::CbOpcode8F() {}

void CPU::CbOpcode90() {}
void CPU::CbOpcode91() {}
void CPU::CbOpcode92() {}
void CPU::CbOpcode93() {}
void CPU::CbOpcode94() {}
void CPU::CbOpcode95() {}
void CPU::CbOpcode96() {}
void CPU::CbOpcode97() {}
void CPU::CbOpcode98() {}
void CPU::CbOpcode99() {}
void CPU::CbOpcode9A() {}
void CPU::CbOpcode9B() {}
void CPU::CbOpcode9C() {}
void CPU::CbOpcode9D() {}
void CPU::CbOpcode9E() {}
void CPU::CbOpcode9F() {}

void CPU::CbOpcodeA0() {}
void CPU::CbOpcodeA1() {}
void CPU::CbOpcodeA2() {}
void CPU::CbOpcodeA3() {}
void CPU::CbOpcodeA4() {}
void CPU::CbOpcodeA5() {}
void CPU::CbOpcodeA6() {}
void CPU::CbOpcodeA7() {}
void CPU::CbOpcodeA8() {}
void CPU::CbOpcodeA9() {}
void CPU::CbOpcodeAA() {}
void CPU::CbOpcodeAB() {}
void CPU::CbOpcodeAC() {}
void CPU::CbOpcodeAD() {}
void CPU::CbOpcodeAE() {}
void CPU::CbOpcodeAF() {}

void CPU::CbOpcodeB0() {}
void CPU::CbOpcodeB1() {}
void CPU::CbOpcodeB2() {}
void CPU::CbOpcodeB3() {}
void CPU::CbOpcodeB4() {}
void CPU::CbOpcodeB5() {}
void CPU::CbOpcodeB6() {}
void CPU::CbOpcodeB7() {}
void CPU::CbOpcodeB8() {}
void CPU::CbOpcodeB9() {}
void CPU::CbOpcodeBA() {}
void CPU::CbOpcodeBB() {}
void CPU::CbOpcodeBC() {}
void CPU::CbOpcodeBD() {}
void CPU::CbOpcodeBE() {}
void CPU::CbOpcodeBF() {}

void CPU::CbOpcodeC0() {}
void CPU::CbOpcodeC1() {}
void CPU::CbOpcodeC2() {}
void CPU::CbOpcodeC3() {}
void CPU::CbOpcodeC4() {}
void CPU::CbOpcodeC5() {}
void CPU::CbOpcodeC6() {}
void CPU::CbOpcodeC7() {}
void CPU::CbOpcodeC8() {}
void CPU::CbOpcodeC9() {}
void CPU::CbOpcodeCA() {}
void CPU::CbOpcodeCB() {}
void CPU::CbOpcodeCC() {}
void CPU::CbOpcodeCD() {}
void CPU::CbOpcodeCE() {}
void CPU::CbOpcodeCF() {}

void CPU::CbOpcodeD0() {}
void CPU::CbOpcodeD1() {}
void CPU::CbOpcodeD2() {}
void CPU::CbOpcodeD3() {}
void CPU::CbOpcodeD4() {}
void CPU::CbOpcodeD5() {}
void CPU::CbOpcodeD6() {}
void CPU::CbOpcodeD7() {}
void CPU::CbOpcodeD8() {}
void CPU::CbOpcodeD9() {}
void CPU::CbOpcodeDA() {}
void CPU::CbOpcodeDB() {}
void CPU::CbOpcodeDC() {}
void CPU::CbOpcodeDD() {}
void CPU::CbOpcodeDE() {}
void CPU::CbOpcodeDF() {}

void CPU::CbOpcodeE0() {}
void CPU::CbOpcodeE1() {}
void CPU::CbOpcodeE2() {}
void CPU::CbOpcodeE3() {}
void CPU::CbOpcodeE4() {}
void CPU::CbOpcodeE5() {}
void CPU::CbOpcodeE6() {}
void CPU::CbOpcodeE7() {}
void CPU::CbOpcodeE8() {}
void CPU::CbOpcodeE9() {}
void CPU::CbOpcodeEA() {}
void CPU::CbOpcodeEB() {}
void CPU::CbOpcodeEC() {}
void CPU::CbOpcodeED() {}
void CPU::CbOpcodeEE() {}
void CPU::CbOpcodeEF() {}

void CPU::CbOpcodeF0() {}
void CPU::CbOpcodeF1() {}
void CPU::CbOpcodeF2() {}
void CPU::CbOpcodeF3() {}
void CPU::CbOpcodeF4() {}
void CPU::CbOpcodeF5() {}
void CPU::CbOpcodeF6() {}
void CPU::CbOpcodeF7() {}
void CPU::CbOpcodeF8() {}
void CPU::CbOpcodeF9() {}
void CPU::CbOpcodeFA() {}
void CPU::CbOpcodeFB() {}
void CPU::CbOpcodeFC() {}
void CPU::CbOpcodeFD() {}
void CPU::CbOpcodeFE() {}
void CPU::CbOpcodeFF() {}